services:
  lab-api:
    build: .

    container_name: lab-api

    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "8000:8000"

    volumes:
      - ./app:/app/app
      - /var/run/docker.sock:/var/run/docker.sock:ro

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

    networks:
      - lab-network

networks:
  lab-network:
    external: true
